In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix+

+
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In [ ]:
# load the Iris dataset
iris = datasets.load_iris()
x = iris.data
y = iris.target

# split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

## create and train the svm model


In [ ]:
# create an SVN classifier with a linear kernel ( you can use other kernels as well)
svm_classifier = SVC(kernel='linear')

# train the model on the training data
svm_classifier.fit(x_train,y_train)

SVC(kernel='linear')

## make predictions on the test set


In [ ]:
# predict the labels for the test set
y_pred = svm_classifier.predict(x_test)

## Evaluate the model's performance

In [ ]:
# calculate accuracy
accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy:.2f}")


#print classification report (precision , recall, F1-score, support)
print(classification_report(y_test, y_pred))

#print confussion matrix

conf_matrix = confusion_matrix(y_test , y_pred)
print("confusion matrx:")
print(conf_matrix)

Accuracy:1.00
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion matrx:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


##Visualize the SVM decision boundary (for 2D